# --- BEGIN LOREM ---
# Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
# incididunt ut labore et dolore magna aliqua.
# --- END LOREM ---
# Some comments at the top.
Contents of Makefile.
